language: node_js
sudo: true
services:
- docker
node_js:
- '8'
- '10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm test
env:
  global:
  - CXX=g++-4.8
